.TH theia· 1 2014-Jan "linux" "end-user command-line use, and options"

.SH NAME
.B theia
\- interactive terminal color configurator for eterm

.SH PATRON
.B theia-euryphaessa
(wide-shinning)
light of the clear blue sky

.SH IMAGERY
glittering woman, mother of helios (sun), selene (moon), and eos (dawn)

.SH SUMMARY
as a c-programmer, i live in gentoo, fluxbox, and eterm.  my visual environment
must be aesthetic and keep me focused and productive.  color is critical as
many of my programs classify data using color-coding.

.SH FOREWARNING
i am a crazy, selfish, dog-fooding c-programmer.  i set unrealistic,
challenging, and audacious goals to push myself; and therefore, my software
tends to be experimental, very personalized, and constantly evolving.

i never planned to share software with end-users, my intention is to expose
my code to other programmers so we may learn from (and laugh at) each other.
use this software at your own risk.  i take zero responsibility ;)

my point is not to be the best, it is to be _my_ best.  to learn how to build
fullsome, transparent, and maintainable software.  my designs and code may
not be universally liked, but i hand-coded _every_ byte ;)

.SH SYNOPSIS
.B theia [URGENTS] [OPTIONS] [ARGUMENTS]

.SH OPTIONS

.B -w, --wide
prints a 240 column color report

.B -n, --narrow
prints a 140 column color report

.B -t, --tiny
prints a 80 column color report

.B -b, --backs
prints a list of options for back colors

.B -r, --runtime
prints a list of known terminals and settings

.SH ARGUMENTS

.B <s>
single/double character [a-z] which is short-hand for a transparent eterm
background color.

.B <xx>
two digit hex id which is short-hand for a font color theme from the file

.B <xxxxxx>
six digit hex color code which directly sets the transparent eterm background
color.

.SH FILES

.I /proc/
.RS 3
theia uses the proc filesystem to locate eterm/hearth pid's
.RE

.I /var/log/yLOG/theia.ttys
.RS 3
contains the current settings for known terminals
.RE

.I /home/system/theia.xwin_terminal_configurator/theia.schemes
.RS 3
contains the options for backgound tints and font color themes
.RE

.SH HERITAGE
theia euryphaessa (wide-shinning) is one of the twelve greek titans and
titaness of sight and the light of the clear blue sky.  she is the consort
of hyperion and mother to helios (sun), selene (moon), and eos (dawn).
she is the goddess who endowed gold, silver, and gems with their
brilliance and intrinsic value.

.SH AUTHOR
heatherly

.SH COLOPHON
this page is part of a documentation package mean to make the use of the
heatherly tools easier and faster

